#=================================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK
#=================================================

name: Build G-DOCK

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clean up Docker images
      run: |
        images=$(docker images -q)
        if [ -n "$images" ]; then
          docker rmi $images
        else
          echo "No Docker images to remove"
        fi

    - name: Install dependencies
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler u-boot-tools


    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede lede

    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cp -f gdockfull128.config ./lede/.config
        chmod +x diy.sh
        cd lede
        ../diy.sh
        make defconfig

    - name: Download package
      run: |
        echo -e "$(nproc) thread build."
        cd lede && make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        cd lede
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: G-DOCK
        path: ./lede/bin
